SELECT FOOD_PRODUCT.PRODUCT_ID, FOOD_PRODUCT.PRODUCT_NAME, SUM(FOOD_ORDER.AMOUNT) * FOOD_PRODUCT.PRICE AS 'TOTAL_SALES'
FROM FOOD_PRODUCT
JOIN FOOD_ORDER ON FOOD_PRODUCT.PRODUCT_ID = FOOD_ORDER.PRODUCT_ID
WHERE DATE_FORMAT(FOOD_ORDER.PRODUCE_DATE, '%Y-%m') = '2022-05'
GROUP BY FOOD_ORDER.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, FOOD_PRODUCT.PRODUCT_ID 
