SELECT PRODUCT.PRODUCT_CODE, (PRODUCT.PRICE * OS.OF_COUNT) AS 'SALES'
FROM PRODUCT
JOIN 
(SELECT PRODUCT.PRODUCT_CODE, PRODUCT.PRODUCT_ID, SUM(OFFLINE_SALE.SALES_AMOUNT) AS 'OF_COUNT'
FROM PRODUCT
JOIN OFFLINE_SALE ON PRODUCT.PRODUCT_ID = OFFLINE_SALE.PRODUCT_ID
GROUP BY OFFLINE_SALE.PRODUCT_ID) AS OS
ON PRODUCT.PRODUCT_ID = OS.PRODUCT_ID
ORDER BY SALES DESC, PRODUCT.PRODUCT_CODE ASC
