SELECT YEAR(ONLINE_SALE.SALES_DATE) AS 'YEAR', MONTH(ONLINE_SALE.SALES_DATE) AS 'MONTH', USER_INFO.GENDER, COUNT(DISTINCT ONLINE_SALE.USER_ID) AS 'USERS'
FROM USER_INFO
JOIN ONLINE_SALE ON USER_INFO.USER_ID = ONLINE_SALE.USER_ID
WHERE USER_INFO.GENDER IS NOT NULL
GROUP BY YEAR(ONLINE_SALE.SALES_DATE), MONTH(ONLINE_SALE.SALES_DATE), GENDER
ORDER BY YEAR, MONTH, GENDER
